{"name": "test_verify_error_notification_with_invalid_password", "status": "passed", "start": 1709473028452, "stop": 1709473028978, "uuid": "28b0286d-1726-4e06-8dbd-0013cfb7fed9", "historyId": "11618e94f4ee8debe8d5587e406202fb", "testCaseId": "11618e94f4ee8debe8d5587e406202fb", "fullName": "Tests.test_login.TestSearch#test_verify_error_notification_with_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearch"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "27156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}