{"name": "test6_verify_error_notification_without_credentials", "status": "passed", "start": 1710525314490, "stop": 1710525314641, "uuid": "c99498a3-ba25-4daf-9fe5-bfa6ca400323", "historyId": "4a4759846ac445ccc3ca9b12d5490ec9", "testCaseId": "4a4759846ac445ccc3ca9b12d5490ec9", "fullName": "Tests.test_login.TestLogin#test6_verify_error_notification_without_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}