{"name": "test_verify_error_notification_with_invalid_password", "status": "passed", "start": 1709527112172, "stop": 1709527112577, "uuid": "7fe64341-96a7-404d-8e13-56efebf49f36", "historyId": "f0b9e4240cd884fe538d23b824b16807", "testCaseId": "f0b9e4240cd884fe538d23b824b16807", "fullName": "Tests.test_login.TestLogin#test_verify_error_notification_with_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "2832-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}